//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuPont.API {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponeString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponeString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DuPont.API.ResponeString", typeof(ResponeString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 响应失败，请稍后重试！ 的本地化字符串。
        /// </summary>
        internal static string AcceptFaile {
            get {
                return ResourceManager.GetString("AcceptFaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号已被锁定 的本地化字符串。
        /// </summary>
        internal static string AccountWasLockedMessage {
            get {
                return ResourceManager.GetString("AccountWasLockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址格式错误! 的本地化字符串。
        /// </summary>
        internal static string AddressError {
            get {
                return ResourceManager.GetString("AddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址必填! 的本地化字符串。
        /// </summary>
        internal static string AddressNotNull {
            get {
                return ResourceManager.GetString("AddressNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改需求状态失败，请稍后重试！ 的本地化字符串。
        /// </summary>
        internal static string ChangeStatusFaile {
            get {
                return ResourceManager.GetString("ChangeStatusFaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误！ 的本地化字符串。
        /// </summary>
        internal static string CodeError {
            get {
                return ResourceManager.GetString("CodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码已过期！ 的本地化字符串。
        /// </summary>
        internal static string CodePastDue {
            get {
                return ResourceManager.GetString("CodePastDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评价失败，请稍后重试！ 的本地化字符串。
        /// </summary>
        internal static string CommentFaile {
            get {
                return ResourceManager.GetString("CommentFaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CropId编号格式不正确! 的本地化字符串。
        /// </summary>
        internal static string CropIdError {
            get {
                return ResourceManager.GetString("CropIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预期时间必填! 的本地化字符串。
        /// </summary>
        internal static string DateNotNull {
            get {
                return ResourceManager.GetString("DateNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除操作失败，请稍候再次尝试。 的本地化字符串。
        /// </summary>
        internal static string DeleteFailedMessage {
            get {
                return ResourceManager.GetString("DeleteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除记录成功。 的本地化字符串。
        /// </summary>
        internal static string DeleteSuccessfullyMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除的记录不存在。 的本地化字符串。
        /// </summary>
        internal static string DeleteWithNonMessage {
            get {
                return ResourceManager.GetString("DeleteWithNonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不满足产业商最低需求! 的本地化字符串。
        /// </summary>
        internal static string DissatisfyBusinessRequire {
            get {
                return ResourceManager.GetString("DissatisfyBusinessRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超过产业商的收购上限! 的本地化字符串。
        /// </summary>
        internal static string ExceedBusinessRequirementCap {
            get {
                return ResourceManager.GetString("ExceedBusinessRequirementCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的记录未能保存成功，请稍后再次尝试。 的本地化字符串。
        /// </summary>
        internal static string InternalErrorMessage {
            get {
                return ResourceManager.GetString("InternalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不要恶意操作！ 的本地化字符串。
        /// </summary>
        internal static string MaliciousProcessing {
            get {
                return ResourceManager.GetString("MaliciousProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不匹配！ 的本地化字符串。
        /// </summary>
        internal static string Mismatching {
            get {
                return ResourceManager.GetString("Mismatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无操作权限！ 的本地化字符串。
        /// </summary>
        internal static string NoJurisdiction {
            get {
                return ResourceManager.GetString("NoJurisdiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择农机手！ 的本地化字符串。
        /// </summary>
        internal static string NoPersonIdsForOperatorRequirement {
            get {
                return ResourceManager.GetString("NoPersonIdsForOperatorRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号不存在! 的本地化字符串。
        /// </summary>
        internal static string NoPhoneNumber {
            get {
                return ResourceManager.GetString("NoPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该需求不存在! 的本地化字符串。
        /// </summary>
        internal static string NoRequirement {
            get {
                return ResourceManager.GetString("NoRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此需求是发布给农机手的您无权响应！ 的本地化字符串。
        /// </summary>
        internal static string NotBAccept {
            get {
                return ResourceManager.GetString("NotBAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该记录已被响应不能删除！ 的本地化字符串。
        /// </summary>
        internal static string NotDelete {
            get {
                return ResourceManager.GetString("NotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此需求是发布给产业商的您无权响应！ 的本地化字符串。
        /// </summary>
        internal static string NotFAccept {
            get {
                return ResourceManager.GetString("NotFAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能重复申请！ 的本地化字符串。
        /// </summary>
        internal static string NotRepeatApplication {
            get {
                return ResourceManager.GetString("NotRepeatApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该需求已被响应，不能修改！ 的本地化字符串。
        /// </summary>
        internal static string NotUpdate {
            get {
                return ResourceManager.GetString("NotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数无效！ 的本地化字符串。
        /// </summary>
        internal static string ParmetersInvalidMessage {
            get {
                return ResourceManager.GetString("ParmetersInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号必填！ 的本地化字符串。
        /// </summary>
        internal static string PhonenumberNotNull {
            get {
                return ResourceManager.GetString("PhonenumberNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询操作失败，请稍后再次尝试。 的本地化字符串。
        /// </summary>
        internal static string QueryFailedMessage {
            get {
                return ResourceManager.GetString("QueryFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询成功。 的本地化字符串。
        /// </summary>
        internal static string QuerySuccessfullyMessage {
            get {
                return ResourceManager.GetString("QuerySuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您查询的记录不存在。 的本地化字符串。
        /// </summary>
        internal static string QueryWithNonMessage {
            get {
                return ResourceManager.GetString("QueryWithNonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码和密码不能为空！ 的本地化字符串。
        /// </summary>
        internal static string RegistrationWithTelephoneNullMessage {
            get {
                return ResourceManager.GetString("RegistrationWithTelephoneNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该需求已被关闭！ 的本地化字符串。
        /// </summary>
        internal static string Requirementclose {
            get {
                return ResourceManager.GetString("Requirementclose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该需求已被响应! 的本地化字符串。
        /// </summary>
        internal static string RequirementOver {
            get {
                return ResourceManager.GetString("RequirementOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色Id不存在 的本地化字符串。
        /// </summary>
        internal static string RoleIdNotExistsMessage {
            get {
                return ResourceManager.GetString("RoleIdNotExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的记录保存成功！ 的本地化字符串。
        /// </summary>
        internal static string SaveSuccessfullyMessage {
            get {
                return ResourceManager.GetString("SaveSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你上传的图片必须是jpg, bmp或者是png格式！ 的本地化字符串。
        /// </summary>
        internal static string UploadFileIsImageMessage {
            get {
                return ResourceManager.GetString("UploadFileIsImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        internal static string UserNotExistsMessage {
            get {
                return ResourceManager.GetString("UserNotExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起购值不能大于收购最大值| 的本地化字符串。
        /// </summary>
        internal static string WeightIsError {
            get {
                return ResourceManager.GetString("WeightIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您不能响应自己发布的需求! 的本地化字符串。
        /// </summary>
        internal static string YourSelfRequirement {
            get {
                return ResourceManager.GetString("YourSelfRequirement", resourceCulture);
            }
        }
    }
}
