//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuPont {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponeString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponeString() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DuPont.ResponeString", typeof(ResponeString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败！ 的本地化字符串。
        /// </summary>
        internal static string AddFaile {
            get {
                return ResourceManager.GetString("AddFaile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功！ 的本地化字符串。
        /// </summary>
        internal static string AddOk {
            get {
                return ResourceManager.GetString("AddOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据服务器错误! 的本地化字符串。
        /// </summary>
        internal static string DBError {
            get {
                return ResourceManager.GetString("DBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部服务器错误！ 的本地化字符串。
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数无效！ 的本地化字符串。
        /// </summary>
        internal static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录用户名已经存在！ 的本地化字符串。
        /// </summary>
        internal static string LoginUserNameExist {
            get {
                return ResourceManager.GetString("LoginUserNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先登录！ 的本地化字符串。
        /// </summary>
        internal static string NotLogin {
            get {
                return ResourceManager.GetString("NotLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号已存在！ 的本地化字符串。
        /// </summary>
        internal static string PhoneNumberExit {
            get {
                return ResourceManager.GetString("PhoneNumberExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功！ 的本地化字符串。
        /// </summary>
        internal static string UpdateOK {
            get {
                return ResourceManager.GetString("UpdateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在！ 的本地化字符串。
        /// </summary>
        internal static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
    }
}
